server:
  port: 8081
logging:
  level:
    org.springframework.ai: DEBUG
    io.modelcontextprotocol: DEBUG
spring:
  application:
    name: ai4j-mcp-spec
  ai:
    mcp:
      server:
        annotation-scanner:
          enabled: true
        type: SYNC
        sse:
          path: /mcp
